least oldest file in my collection

diff --git a/healhcheck_wn_condor b/healhcheck_wn_condor
--- a/healhcheck_wn_condor
+++ b/healhcheck_wn_condor
@@ -9,19 +9,17 @@
 DATE=$(date)
 PROGRAM=`basename $0`
 SHOSTNAME=$(hostname -s)
-Nmesg=""				# per test message
-TellNagios="All_OK"			# What to tell nagios
-mesg="NODE_IS_HEALTHY = True"		# Default OK to condor
-test_file="/pool/condor/andrewIsGreat"	# A test file name
-rc=0					# exit code, 0 by default
+Nmesg=""                                # per test message
+TellNagios="All_OK"                     # What to tell nagios
+mesg="NODE_IS_HEALTHY = True"           # Default OK to condor
+test_file="/pool/condor/andrewIsGreat"  # A test file name
+rc=0                                    # exit code, 0 by default
 upfoo=0                                 # Uptime variable
-exit_code=0				# script and nagios exit code
-LOGGER="/usr/bin/env logger"		# logger program
-log_message="Failed healthcheck:"	# log message preamble
-debug_val=0				# to debug or not debug ?
+exit_code=0                             # script and nagios exit code
+LOGGER="/usr/bin/env logger"            # logger program
+log_message="Failed healthcheck:"       # log message preamble
+debug_val=0                             # to debug or not debug ?
 NAGIOS_SERVER="130.246.180.225"         # Nagios server obviously
-TIME_SERVER="130.246.8.13"          	# time server obviously
-time_secs=2	           		# allowed time drift
 typeset -i no_dead_guys                 # number of dead cvmfs repos
 declare -a dead_guys                    # Array to hold dead cvmfs user regex
 declare -a file_systems                 # Array to hold list of filesystems
@@ -52,44 +50,45 @@ function debug() {
         fi
 }
 
+
 # We only want debug - nothing else.
 if [ $# -gt 0 ]
 then
-	echo ""
-	echo "Wrong input for $PROGRAM, -d is the only option"
-	exit 3
+        echo ""
+        echo "Wrong input for $PROGRAM, -d is the only option"
+        exit 3
 fi
 
 function tell_and_die() {
-	# function called to deal with critical condition.
-	# no dead repos or more than 2 dead repos
-	if [ $no_dead_guys -ge 2 -o $no_dead_guys -le 0 ]	# more than 2 dead repos
-	then
-		mesg="NODE_IS_HEALTHY = False"	# Message for condor
-		TellNagios=$@			# Message for nagios
-		exit_code=2 			# Nagios critical
-		echo $mesg			# standard out to condor
-		echo "NODE_STATUS = \"$TellNagios\""
-		log_message="$log_message  ${TellNagios}" 	# log message
-	else
-		for dead in ${dead_guys[@]}
-		do
-		mesg="$mesg && (regexp(\"$dead\", Owner) =?= False)"
-		done
-		TellNagios=$@			# Message for nagios
-		exit_code=1 			# Nagios warn
-		echo $mesg			# standard out to condor
-		echo "NODE_STATUS = \"$TellNagios\""
-		log_message="$log_message  $TellNagios" 	# log message
-	fi
-	if [ $debug_val -gt 0 ] 	# if debug, we want to know what is going on
-  	then
-		echo $log_message
-		return
-	fi
-	/bin/echo -e "${SHOSTNAME}\tCondor Health check\t${exit_code}\t${TellNagios}"| /usr/sbin/send_nsca -H 130.246.180.225 -c /etc/nagios/send_nsca.cfg >/dev/null
-	$LOGGER $log_message
-	exit ${exit_code}
+        # function called to deal with critical condition.
+        # no dead repos or more than 2 dead repos
+        if [ $no_dead_guys -ge 2 -o $no_dead_guys -le 0 ]       # more than 2 dead repos
+        then
+                mesg="NODE_IS_HEALTHY = False"  # Message for condor
+                TellNagios=$@                   # Message for nagios
+                exit_code=2                     # Nagios critical
+                echo $mesg                      # standard out to condor
+                echo "NODE_STATUS = \"$TellNagios\""
+                log_message="$log_message  ${TellNagios}"       # log message
+        else
+                for dead in ${dead_guys[@]}
+                do
+                mesg="$mesg && (regexp(\"$dead\", Owner) =?= False)"
+                done
+                TellNagios=$@                   # Message for nagios
+                exit_code=1                     # Nagios warn
+                echo $mesg                      # standard out to condor
+                echo "NODE_STATUS = \"$TellNagios\""
+                log_message="$log_message  $TellNagios"         # log message
+        fi
+        if [ $debug_val -gt 0 ]         # if debug, we want to know what is going on
+        then
+                echo $log_message
+                return
+        fi
+        /bin/echo -e "${SHOSTNAME}\tCondor Health check\t${exit_code}\t${TellNagios}"| /usr/sbin/send_nsca -H 130.246.180.225 -c /etc/nagios/send_nsca.cfg >/dev/null
+        $LOGGER $log_message
+        exit ${exit_code}
 }
 
 debug "starting ${PROGRAM} on ${DATE}"
@@ -98,15 +97,14 @@ debug "starting ${PROGRAM} on ${DATE}"
 # This test depends on the nagios check_cvmfs script being available, so check first
 if [ ! -f /usr/lib/nagios/plugins/tier1/check_cvmfs2.sh ]
 then
-	Nmesg="Problem: check cvmfs2.sh not available"
+        Nmesg="Problem: check cvmfs2.sh not available"
         tell_and_die $Nmesg
 fi
-
 # Specifically check for grid.cern.ch as it is now supplying our middle ware
 debug "Checking grid.cern.ch"
 if [ $debug_val -gt 0 ]
 then
-        /usr/lib/nagios/plugins/tier1/check_cvmfs2.sh grid.cern.ch 
+        /usr/lib/nagios/plugins/tier1/check_cvmfs2.sh grid.cern.ch
         rc=$?
 else
         /usr/lib/nagios/plugins/tier1/check_cvmfs2.sh grid.cern.ch  >/dev/null 2>&1
@@ -120,26 +118,25 @@ then
 fi
 # End of check for grid.cern.ch
 
-
 debug "CVMFS check for selected VOs"
 for vo in  "${!vos[@]}"
 do
 
-	debug "Checking $vo"
-	if [ $debug_val -gt 0 ]
-	then
-		/usr/lib/nagios/plugins/tier1/check_cvmfs2.sh $vo
-		rc=$?
-	else
-		/usr/lib/nagios/plugins/tier1/check_cvmfs2.sh $vo >/dev/null 2>&1
-		rc=$?
-	fi
+        debug "Checking $vo"
+        if [ $debug_val -gt 0 ]
+        then
+                /usr/lib/nagios/plugins/tier1/check_cvmfs2.sh $vo
+                rc=$?
+        else
+                /usr/lib/nagios/plugins/tier1/check_cvmfs2.sh $vo >/dev/null 2>&1
+                rc=$?
+        fi
 
-	if [ $rc -gt 0 ]
-	then
-		Nmesg="${Nmesg} Problem: CVMFS for ${vo} "
-		dead_guys=("${dead_guys[@]}" ${vos[$vo]})
-	fi
+        if [ $rc -gt 0 ]
+        then
+                Nmesg="${Nmesg} Problem: CVMFS for ${vo} "
+                dead_guys=("${dead_guys[@]}" ${vos[$vo]})
+        fi
 done
 
 # lets see if we got any dead_guys
@@ -155,8 +152,8 @@ fi
 debug "Testing for writable /pool/condor"
 if [ ! -d /pool/condor ]  # no condor dir
 then
-	Nmesg="Problem: No condor scratch area"
-	tell_and_die $Nmesg
+        Nmesg="Problem: No condor scratch area"
+        tell_and_die $Nmesg
 fi
 
 trap "rm -f $test_file; exit" INT TERM EXIT
@@ -167,31 +164,31 @@ trap - INT TERM EXIT
 
 if [ $rc -gt 0 ]
 then
-	Nmesg="Problem: Condor cant write to condor scratch area"
-	tell_and_die $Nmesg
+        Nmesg="Problem: Condor cant write to condor scratch area"
+        tell_and_die $Nmesg
 else
-	debug "condor scratch area is writable"
+        debug "condor scratch area is writable"
 fi
 
 # check swap
 # This test depends on the nagios check_swap script being available, so check first
 if [ ! -f /usr/lib64/nagios/plugins/check_swap ]
 then
-	Nmesg="Problem: No check swap script available"
+        Nmesg="Problem: No check swap script available"
         tell_and_die $Nmesg
 fi
 debug "Testing swap free"
 if [ $debug_val -gt 0 ]
 then
-	/usr/lib64/nagios/plugins/check_swap -w 25% -c 20%
-	rc=$?
+        /usr/lib64/nagios/plugins/check_swap -w 25% -c 20%
+        rc=$?
 else
-	/usr/lib64/nagios/plugins/check_swap -w 25% -c 20% >/dev/null 2>&1
-	rc=$?
+        /usr/lib64/nagios/plugins/check_swap -w 25% -c 20% >/dev/null 2>&1
+        rc=$?
 fi
 if [ $rc -gt 0 ]
 then
-	Nmesg="Problem: Swap in use, less than 25% free"
+        Nmesg="Problem: Swap in use, less than 25% free"
         tell_and_die $Nmesg
 fi
 
@@ -200,22 +197,22 @@ fi
 # so check first
 if [ ! -f /usr/lib64/nagios/plugins/check_disk ]
 then
-	Nmesg="Problem: No check disk script available"
+        Nmesg="Problem: No check disk script available"
         tell_and_die $Nmesg
 fi
 
 debug "Testing space on /pool"
 if [ $debug_val -gt 0 ]
 then
-	/usr/lib64/nagios/plugins/check_disk  -c 5000 -p /pool
-	rc=$?
+        /usr/lib64/nagios/plugins/check_disk  -c 5000 -p /pool
+        rc=$?
 else
-	/usr/lib64/nagios/plugins/check_disk  -c 5000 -p /pool >/dev/null 2>&1
-	rc=$?
+        /usr/lib64/nagios/plugins/check_disk  -c 5000 -p /pool >/dev/null 2>&1
+        rc=$?
 fi
 if [ $rc -gt 0 ]
 then
-	Nmesg="Problem: less than 5000Mb free on /pool"
+        Nmesg="Problem: less than 5000Mb free on /pool"
         tell_and_die $Nmesg
 fi
 
@@ -225,7 +222,13 @@ file_systems=`df -lh -x fuse | sed -ne '/^\/dev/s/^.*\% \([^ ]*\)$/\1/p'`
 
 for dir in ${file_systems[@]}
 do
-        debug "Testing %age space free on $dir"
+	# We want to skip nubes-context cos it is always 100%
+	if [ $dir == "/etc/nubes-context" ]
+	then
+		debug "Skipping $dir because we dont want it"
+		continue
+	fi
+
         if [ $debug_val -gt 0 ]
         then
                 /usr/lib64/nagios/plugins/check_disk  -c 5% -p $dir
@@ -237,8 +240,8 @@ do
 
         if [ $rc -gt 0 ]
         then
-		debug "less than 5% free on $dir"
-		Nmesg="${Nmesg} Problem: less than 5% free on $dir "
+                debug "less than 5% free on $dir"
+                Nmesg="${Nmesg} Problem: less than 5% free on $dir "
         fi
 done
 if [ ! -z "$Nmesg" ]
@@ -250,24 +253,24 @@ fi
 # Check cgroups.
 cg_enabled=$(condor_config_val BASE_CGROUP 2>/dev/null)
 debug "condor_config_val for BASE_CGROUP is: $cg_enabled"
-if [ ! -z $cg_enabled ] 
-	then
-	rc=0
+if [ ! -z $cg_enabled ]
+        then
+        rc=0
         if [ $debug_val -gt 0 ]
         then
-		echo -ne "cgconfig status is: "
-		/sbin/service cgconfig status	
+                echo -ne "cgconfig status is: "
+                /sbin/service cgconfig status
                 rc=$?
         else
-		/sbin/service cgconfig status >/dev/null 2>&1
+                /sbin/service cgconfig status >/dev/null 2>&1
                 rc=$?
         fi
-	if [ $rc -gt 0 ]
-	then
-		debug "cgroups configured in condor but cgconfig not running"
-		Nmesg="${Nmesg} Problem: cgconfig not running"
-        	tell_and_die $Nmesg
-	fi
+        if [ $rc -gt 0 ]
+        then
+                debug "cgroups configured in condor but cgconfig not running"
+                Nmesg="${Nmesg} Problem: cgconfig not running"
+                tell_and_die $Nmesg
+        fi
 fi
 # End Check cgroupgs
 
@@ -282,33 +285,8 @@ fi
 upfoo=$(uptime | awk '{if (match($4, "min")) print $3 ; else print "100"}')
 if [ $upfoo -le 10 ]
 then
-	Nmesg="Problem: Machine up less than 10 minutes."
+        Nmesg="Problem: Machine up less than 10 minutes."
         tell_and_die $Nmesg
-fi
-
-# check time offset
-rc=0 	# reset $rc
-debug "Testing for ntp drift"
-if [ ! -f /usr/lib64/nagios/plugins/check_ntp ]
-then
-	Nmesg="Problem: No check ntp script available"
-        tell_and_die $Nmesg
-fi
-
-if [ $debug_val -gt 0 ]
-        then
-	/usr/lib64/nagios/plugins/check_ntp -H ${TIME_SERVER} -c ${time_secs} 
-	rc=$?
-else
-	/usr/lib64/nagios/plugins/check_ntp -H ${TIME_SERVER} -c ${time_secs} > /dev/null 2>&1
-	rc=$?
-fi
-# Now deal with the answer.
-if [ $rc -gt 0 ]
-then
-	debug "There is more than $time_secs seconds drift"
-	Nmesg="Problem: Time drift error"
-	tell_and_die $Nmesg
 fi
 
 ## End of checks
@@ -324,4 +302,5 @@ echo $mesg
 echo "NODE_STATUS = \"$TellNagios\""
 # exit
 exit ${exit_code}
+
 
