Moved the development script to be the main one.

diff --git a/healhcheck_wn_condor b/healhcheck_wn_condor
--- a/healhcheck_wn_condor
+++ b/healhcheck_wn_condor
@@ -1,55 +1,58 @@
-#!/bin/sh
-#  Worker node health check script, to run from condor startd
+#!/bin/bash
+#
+# This script takes over most of the nagios checks and actions. 
+# There can be soft errors or hard errors, with appropriate actions
 #
 # Note to explain healhcheck script with per VO disabling.
 # If we want to disable jobs starts on a per VO basis the script needs to return something like:
 # NODE_IS_HEALTHY = True && (regexp("atl", Owner) =!= False) && (regexp("cms", Owner) =!= False)
-#declarations
+
+# Variable Declarations
 DATE=$(date)
 PROGRAM=`basename $0`
 SHOSTNAME=$(hostname -s)
-Nmesg=""                                # per test message
-TellNagios="All_OK"                     # What to tell nagios
-mesg="NODE_IS_HEALTHY = True"           # Default OK to condor
-test_file="/pool/condor/andrewIsGreat"  # A test file name
-rc=0                                    # exit code, 0 by default
-typeset -i upfoo=0                      # Uptime variable
-typeset -i uptime=10			# Uptime we check for in mins 
-typeset -i exit_code=0                  # script and nagios exit code
-LOGGER="/usr/bin/env logger"            # logger program
-log_message="Failed healthcheck:"       # log message preamble
-typeset -i debug_val=0                  # to debug or not debug ?
-NAGIOS_SERVER="130.246.180.225"         # Nagios server obviously
-TIME_SERVER="time.rl.ac.uk" 		# The RAL time server
-typeset -i no_dead_guys=0               # number of dead cvmfs repos
-declare -a dead_guys                    # Array to hold dead cvmfs user regex
-declare -a file_systems                 # Array to hold list of filesystems
-typeset -i VIRTUAL_WORKER=0   	    	# Is the node a virtual node? 
+NAGIOS_SERVER="130.246.180.225" # Nagios server obviously
+CONDOR_MESG="NODE_IS_HEALTHY = True"    # Message to Condor, default OK
+NAGIOS_MESG="All_OK"		# Message to nagios, default OK
+LOGGER="/usr/bin/env logger"    # logger program
+LOG_MESG="Failed healthcheck:"  # log message preamble, to be extended in script
+TEST_MESG=""			# What the test says.
+TIME_SERVER="time.rl.ac.uk"     # The RAL time server
+TEST_FILE="/pool/condor/andrewIsGreat"  # A test file name
+CG_ENABLED=""			# Variable used to check cgroups - its a string
+typeset -i RC=0			# Return code from other scripts / progs
+typeset -i DEBUG_VAL=0		# Are we debugging
+typeset -i EXIT_CODE=0		# Exit code for script and nagios
+typeset -i VIRTUAL_WORKER=0     # Is the node a virtual node 
+typeset -i UPTIME_TEST_VAL=10   # minimum uptime for machine
+typeset -i UPTIME_VAL=10        # actual uptime for machine
+typeset -i VIRTUAL_WORKER=0	# Is this a VM
+declare -a FILE_SYSTEMS         # Array to hold list of filesystems
+declare -a DEAD_REPO_USERS	# Array to hold list of dead repo users
 # we need a hash to map VOs to regex -  Only declare it once
-declare -A vos
-vos["atlas.cern.ch"]=atl
-vos["atlas-condb.cern.ch"]=atl
-vos["cms.cern.ch"]=cms
-vos["lhcb.cern.ch"]=lhcb
-vos["alice.cern.ch"]=alice
-# End declarations.
+declare -A VOS
+VOS["atlas.cern.ch"]=atl
+VOS["atlas-condb.cern.ch"]=atl
+VOS["cms.cern.ch"]=cms
+VOS["lhcb.cern.ch"]=lhcb
+VOS["alice.cern.ch"]=alice
+# End Variable Declarations
 
-# first check for debug on command line.
+# House keeping 
+# first check for debug on command line. It is useful to be able to run this in debug mode
 case "$1" in
         -d|--debug)
-             debug_val=1
+             DEBUG_VAL=1
               shift
               ;;
 esac
 
 function debug() {
-        if [ $debug_val -gt 0 ]
+        if [ $DEBUG_VAL -gt 0 ]
         then
-                echo
                 echo "DEBUG: $@"
         fi
 }
-
 
 # We only want debug - nothing else.
 if [ $# -gt 0 ]
@@ -58,293 +61,309 @@ then
         echo "Wrong input for $PROGRAM, -d is the only option"
         exit 3
 fi
+# End of housekeeping
 
-function tell_and_die() {
-        # function called to deal with critical condition.
-        # 0 dead repos or more than 2 dead repos
-        if [ $no_dead_guys -eq 0 -o $no_dead_guys -gt 2 ]       # more than 2 dead repos
-        then							# Just die with errors
-                mesg="NODE_IS_HEALTHY = False"  # Message for condor
-                TellNagios=$@                   # Message for nagios
-                exit_code=2                     # Nagios critical
-                echo $mesg                      # standard out to condor
-                echo "NODE_STATUS = \"$TellNagios\""
-                log_message="$log_message  ${TellNagios}"       # log message
-        else
-                for dead in ${dead_guys[@]}
-                do
-                mesg="$mesg && (regexp(\"$dead\", Owner) =?= False)"
-                done
-                TellNagios=$@                   # Message for nagios
-                exit_code=1                     # Nagios warn
-                echo $mesg                      # standard out to condor
-                echo "NODE_STATUS = \"$TellNagios\""
-                log_message="$log_message  $TellNagios"         # log message
+# Start of functions
+function fatal_exit() {
+	# function to deal with a fatal test failure
+	NAGIOS_MESG=$@
+        CONDOR_MESG="NODE_IS_HEALTHY = False"  # Message for condor
+	EXIT_CODE=2
+	echo $CONDOR_MESG                      # standard out to condor
+	echo "NODE_STATUS = \"$NAGIOS_MESG\""
+	LOG_MESG="$LOG_MESG  ${NAGIOS_MESG}"       # log message
+        if [ $DEBUG_VAL -gt 0 ]         # if debug, we want to know what is going on
+        then				# And we want to continue wth the other tests
+                echo "EXIT_CODE    ${EXIT_CODE}"
+		echo 
+		echo "Normally exit here === Continuing in debug mode ==="
+		echo 
+		return    		# We want to do all the tests in debug mode, so return for more 
+	else	# no debug, so send nsca and write log message and exit
+		/bin/echo -e "${SHOSTNAME}\tCondor Health check\t${EXIT_CODE}\t${NAGIOS_MESG}"| /usr/sbin/send_nsca -H ${NAGIOS_SERVER} -c /etc/nagios/send_nsca.cfg >/dev/null
+		if [  -n "$LOG_MESG" ]		# log what we do the syslog.
+		then
+			$LOGGER $LOG_MESG
+		fi
+		exit ${EXIT_CODE}
         fi
-        if [ $debug_val -gt 0 ]         # if debug, we want to know what is going on
-        then
-                echo $log_message
-		exit ${exit_code}
-        fi
-        /bin/echo -e "${SHOSTNAME}\tCondor Health check\t${exit_code}\t${TellNagios}"| /usr/sbin/send_nsca -H 130.246.180.225 -c /etc/nagios/send_nsca.cfg >/dev/null
-        $LOGGER $log_message
-        exit ${exit_code}
 }
+# End of functions.
 
+# Start work
 debug "starting ${PROGRAM} on ${DATE}"
 
 # Check if we are on a vm
-if ( grep -q workernode-virtual /etc/motd )    
+if ( grep -q workernode-virtual /etc/motd )
 then
-    VIRTUAL_WORKER=1			# Is the node a virtual node?
-    uptime=2
+    VIRTUAL_WORKER=1                    # Is the node a virtual node?
+    UPTIME_TEST_VAL=2
 else
     VIRTUAL_WORKER=0
-    uptime=10
+    UPTIME_TEST_VAL=10
 fi
-
 debug "VIRTUAL_WORKER is $VIRTUAL_WORKER"
-debug "\$uptime is $uptime"
+debug "\$UPTIME_TEST_VAL is $UPTIME_TEST_VAL"
+# End of vm Checks
 
+# Start of checks - Fatal checks first.
+# The first check to fire ends the script except in debug mode.
 
-# Cvmfs check for major VOs.
-# This test depends on the nagios check_cvmfs script being available, so check first
-if [ ! -f /usr/lib/nagios/plugins/tier1/check_cvmfs2.sh ]
-then
-        Nmesg="Problem: check cvmfs2.sh not available"
-        tell_and_die $Nmesg
+# Uptime check
+debug "Testing uptime is > $UPTIME_TEST_VAL mins"
+if [ $DEBUG_VAL -gt 0 ]
+        then
+        uptime  | awk '{print "Machine up: " $3 " " $4}'
 fi
-# Specifically check for grid.cern.ch as it is now supplying our middle ware
-debug "Checking grid.cern.ch"
-if [ $debug_val -gt 0 ]
+
+UPTIME_VAL=$(uptime | awk '{if (match($4, "min")) print $3 ; else print "100"}')
+if [ $UPTIME_VAL -le $UPTIME_TEST_VAL ]
 then
-        /usr/lib/nagios/plugins/tier1/check_cvmfs2.sh grid.cern.ch
-        rc=$?
+        fatal_exit "Problem: Machine up less than $UPTIME_TEST_VAL minutes."
+fi
+# end of uptime check
+
+# Test for file /etc/condor/pool_password
+debug "Checking /etc/condor/pool_password"
+if [ ! -s /etc/condor/pool_password ] 
+then
+	fatal_exit "No or zero sized pool_password file found"
+fi
+# End of pool_password check
+
+# test for time
+debug "Testing system time against ${TIME_SERVER}"
+# check the nagios plugin test exists 
+if [ ! -f /usr/lib64/nagios/plugins/check_ntp_time ]
+then
+         fatal_exit "Problem: No check time script available"
+fi
+if [ $DEBUG_VAL -gt 0 ]
+then
+        /usr/lib64/nagios/plugins/check_ntp_time -c 1 -H ${TIME_SERVER}
+        RC=$?
 else
-        /usr/lib/nagios/plugins/tier1/check_cvmfs2.sh grid.cern.ch  >/dev/null 2>&1
-        rc=$?
+        /usr/lib64/nagios/plugins/check_ntp_time -c 1 -H ${TIME_SERVER} >/dev/null 2>&1
+        RC=$?
 fi
 
-if [ $rc -gt 0 ]
+if [ $RC -gt 0 ]
 then
-        Nmesg="${Nmesg} Problem: CVMFS for grid.cern.ch failed"
-        tell_and_die $Nmesg
+        fatal_exit "Problem: machine clock more than 1 second out" 
 fi
-# End of check for grid.cern.ch
-
-debug "CVMFS check for selected VOs"
-for vo in  "${!vos[@]}"
-do
-
-        debug "Checking $vo"
-        if [ $debug_val -gt 0 ]
-        then
-                /usr/lib/nagios/plugins/tier1/check_cvmfs2.sh $vo
-                rc=$?
-        else
-                /usr/lib/nagios/plugins/tier1/check_cvmfs2.sh $vo >/dev/null 2>&1
-                rc=$?
-        fi
-
-        if [ $rc -gt 0 ]
-        then
-                Nmesg="${Nmesg} Problem: CVMFS for ${vo} "
-                dead_guys=("${dead_guys[@]}" ${vos[$vo]})
-        fi
-done
-
-# lets see if we got any dead_guys
-no_dead_guys=${#dead_guys[@]}
-
-debug "After checking CVMFS, the \$no_dead_guys is $no_dead_guys"
-if [ $no_dead_guys -gt 0 ]
-then
-        tell_and_die $Nmesg
-fi
-# end of cvmfs checks
+# end of time check. 
 
 # Read-only filesystem check. Cant run the whole thing cos we would need root.
-# But we can check a condor directory.
+# But we can check the condor directory.
 debug "Testing for writable /pool/condor"
 if [ ! -d /pool/condor ]  # no condor dir
 then
-        Nmesg="Problem: No condor scratch area"
-        tell_and_die $Nmesg
+        fatal_exit "Problem: No condor scratch area"
 fi
 
-trap "rm -f $test_file; exit" INT TERM EXIT
-touch ${test_file} 1> /dev/null 2>&1
-rc=$?
-rm -f ${test_file} > /dev/null 2>&1
+trap "rm -f $TEST_FILE; exit" INT TERM EXIT
+touch ${TEST_FILE} 1> /dev/null 2>&1
+RC=$?
+rm -f ${TEST_FILE} > /dev/null 2>&1
 trap - INT TERM EXIT
 
-if [ $rc -gt 0 ]
+if [ $RC -gt 0 ]
 then
-        Nmesg="Problem: Condor cant write to condor scratch area"
-        tell_and_die $Nmesg
+        fatal_exit "Problem: Condor cant write to condor scratch area"
 else
-        debug "condor scratch area is writable"
+        debug "OK condor scratch area is writable"
 fi
+# end of read-only filesystem check
 
-if [[ $VIRTUAL_WORKER -ne 1 ]] 
+# check swap but not on vitual machines
+if [[ $VIRTUAL_WORKER -ne 1 ]]
 then
-    # check swap
     # This test depends on the nagios check_swap script being available, so check first
     if [ ! -f /usr/lib64/nagios/plugins/check_swap ]
     then
-            Nmesg="Problem: No check swap script available"
-            tell_and_die $Nmesg
+            fatal_exit "Problem: No nagios check swap script available"
     fi
     debug "Testing swap free"
-    if [ $debug_val -gt 0 ]
+    if [ $DEBUG_VAL -gt 0 ]
     then
             /usr/lib64/nagios/plugins/check_swap -w 25% -c 20%
-            rc=$?
+            RC=$?
     else
             /usr/lib64/nagios/plugins/check_swap -w 25% -c 20% >/dev/null 2>&1
-            rc=$?
+            RC=$?
     fi
-    if [ $rc -gt 0 ]
+    if [ $RC -gt 0 ]
     then
-            Nmesg="Problem: Swap in use, less than 25% free"
-            tell_and_die $Nmesg
+            fatal_exit "Problem: Swap in use, less than 25% free"
     fi
 fi
+# End of check swap.
+
+# Specifically check for grid.cern.ch as it is now supplying our middle ware
+debug "Checking  CVMFS grid.cern.ch"
+# This test depends  on the nagios check_cvmfs script being available,
+# so check first
+if [ ! -f /usr/lib/nagios/plugins/tier1/check_cvmfs2.sh ]
+then
+	debug "script, /usr/lib64/nagios/plugins/check_disk not available"
+        fatal_exit "Problem: No check cvmfs script available"
+fi
+if [ $DEBUG_VAL -gt 0 ]
+then
+        /usr/lib/nagios/plugins/tier1/check_cvmfs2.sh grid.cern.ch
+        RC=$?
+else
+        /usr/lib/nagios/plugins/tier1/check_cvmfs2.sh grid.cern.ch  >/dev/null 2>&1
+        RC=$?
+fi
+
+if [ $RC -gt 0 ]
+then
+        fatal_exit "Problem: CVMFS for grid.cern.ch failed"
+fi
+# End of check for grid.cern.ch
+
 
 # check disk pool
 # This test  and the next one depends on the nagios check_disk script being available,
 # so check first
 if [ ! -f /usr/lib64/nagios/plugins/check_disk ]
 then
-        Nmesg="Problem: No check disk script available"
-        tell_and_die $Nmesg
+	debug "script, /usr/lib64/nagios/plugins/check_disk not available"
+        fatal_exit "Problem: No check disk script available"
 fi
 
 debug "Testing space on /pool"
-if [ $debug_val -gt 0 ]
+if [ $DEBUG_VAL -gt 0 ]
 then
         /usr/lib64/nagios/plugins/check_disk  -c 5000 -p /pool
-        rc=$?
+        RC=$?
 else
         /usr/lib64/nagios/plugins/check_disk  -c 5000 -p /pool >/dev/null 2>&1
-        rc=$?
+        RC=$?
 fi
-if [ $rc -gt 0 ]
+if [ $RC -gt 0 ]
 then
-        Nmesg="Problem: less than 5000Mb free on /pool"
-        tell_and_die $Nmesg
+        fatal_exit "Problem: less than 5000Mb free on /pool"
 fi
+# End of check on /pool
 
 # Check all other filesystems have at least 5% free.
 # Note that this purposely does not check cvmfs or rather fuse
-file_systems=`df -lh -x fuse | sed -ne '/^\/dev/s/^.*\% \([^ ]*\)$/\1/p'`
+# And there is an exception for /etc/nubes-context
 
-for dir in ${file_systems[@]}
+FILE_SYSTEMS=`df -lh -x fuse | sed -ne '/^\/dev/s/^.*\% \([^ ]*\)$/\1/p'`
+debug "Testing local filesystems for min 5% free space"
+for dir in ${FILE_SYSTEMS[@]}
 do
-	# We want to skip nubes-context cos it is always 100%
-	if [ $dir == "/etc/nubes-context" ]
-	then
-		debug "Skipping $dir because we dont want it"
-		continue
-	fi
+        # We want to skip nubes-context cos it is always 100%
+        if [ $dir == "/etc/nubes-context" ]
+        then
+                debug "Skipping $dir because we dont want it"
+                continue
+        fi
 
-        if [ $debug_val -gt 0 ]
+        if [ $DEBUG_VAL -gt 0 ]
         then
                 /usr/lib64/nagios/plugins/check_disk  -c 5% -p $dir
-                rc=$?
+                RC=$?
         else
                 /usr/lib64/nagios/plugins/check_disk  -c 5% -p $dir >/dev/null 2>&1
-                rc=$?
+                RC=$?
         fi
 
-        if [ $rc -gt 0 ]
+        if [ $RC -gt 0 ]
         then
                 debug "less than 5% free on $dir"
-                Nmesg="${Nmesg} Problem: less than 5% free on $dir "
+                TEST_MESG="${TEST_MESG} Problem: less than 5% free on $dir "
         fi
 done
-if [ ! -z "$Nmesg" ]
+if [ ! -z "$TEST_MESG" ]
 then
-        tell_and_die $Nmesg
+        fatal_ext $TEST_MESG
 fi
 # End of filesystems check
 
 # Check cgroups.
-cg_enabled=$(condor_config_val BASE_CGROUP 2>/dev/null)
-debug "condor_config_val for BASE_CGROUP is: $cg_enabled"
-if [ ! -z $cg_enabled ]
+debug "Testing cgroups"
+CG_ENABLED=$(condor_config_val BASE_CGROUP 2>/dev/null)
+debug "condor_config_val for BASE_CGROUP is: $CG_ENABLED"
+if [ ! -z $CG_ENABLED ]
         then
-        rc=0
-        if [ $debug_val -gt 0 ]
+        RC=0
+        if [ $DEBUG_VAL -gt 0 ]
         then
-                echo -ne "cgconfig status is: "
+                debug "cgconfig status is: "
                 /sbin/service cgconfig status
-                rc=$?
+                RC=$?
         else
                 /sbin/service cgconfig status >/dev/null 2>&1
-                rc=$?
+                RC=$?
         fi
-        if [ $rc -gt 0 ]
+        if [ $RC -gt 0 ]
         then
                 debug "cgroups configured in condor but cgconfig not running"
-                Nmesg="${Nmesg} Problem: cgconfig not running"
-                tell_and_die $Nmesg
+                fatal_exit "Problem: cgconfig not running"
         fi
 fi
 # End Check cgroupgs
 
+## Non-fatal checks these don't call fatal_exit but simply set NAGIOS_MESG,  
+## CONDOR_MESG and EXIT_CODE and exit 
 
-# test for time
-debug "Testing system time against ${TIME_SERVER}"
-# check the file exists 
-if [ ! -f /usr/lib64/nagios/plugins/check_ntp_time ]
-then
-        Nmesg="Problem: No check time script available"
-        tell_and_die $Nmesg
-fi
-if [ $debug_val -gt 0 ]
-then
-	/usr/lib64/nagios/plugins/check_ntp_time -c 1 -H ${TIME_SERVER}
-	rc=$?
-else
-	/usr/lib64/nagios/plugins/check_ntp_time -c 1 -H ${TIME_SERVER} >/dev/null 2>&1
-	rc=$?
-fi
-
-if [ $rc -gt 0 ]
-then
-        Nmesg="Problem: machine clock more than 1 second out"
-        tell_and_die $Nmesg
-fi
-# end of time check. 
-
-
-# Uptime check
-debug "Testing uptime is > $uptime mins"
-if [ $debug_val -gt 0 ]
+# Check CVMFS for selected VOs
+debug "CVMFS check for selected VOs"
+for vo in  "${!VOS[@]}"
+do
+        debug "Checking $vo"
+        if [ $DEBUG_VAL -gt 0 ]
         then
-        uptime  | awk '{print "Machine up: " $3 " " $4}'
-fi
+                /usr/lib/nagios/plugins/tier1/check_cvmfs2.sh $vo
+                RC=$?
+        else
+                /usr/lib/nagios/plugins/tier1/check_cvmfs2.sh $vo >/dev/null 2>&1
+                RC=$?
+        fi
 
-upfoo=$(uptime | awk '{if (match($4, "min")) print $3 ; else print "100"}')
-if [ $upfoo -le $uptime ]
+        if [ $RC -ne 0 ]
+        then
+                TEST_MESG="${TEST_MESG} Problem: CVMFS for $vo"
+                DEAD_REPO_USERS=("${DEAD_REPO_USERS[@]}" "${VOS[$vo]}")
+        fi
+done
+
+# lets see if we got any DEAD_REPO_USERS
+# if more than 2, it is a fatal_exit 
+# if only 1 or 2 ,  set CONDOR_MESG, NAGIOS_MESG and EXIT_CODE appropriately
+debug "After checking CVMFS, the number of problem users is ${#DEAD_REPO_USERS[@]}"
+if [ ${#DEAD_REPO_USERS[@]} -gt 2 ]
 then
-        Nmesg="Problem: Machine up less than $uptime minutes."
-        tell_and_die $Nmesg
-fi
+	NAGIOS_MESG=$TEST_MESG
+	fatal_exit "More that 2 CVMFS repo broken"
 
-## End of checks
-
-# Default OK
-# first tell nagger, but only if not running debug.
-if [ $debug_val -eq  0 ]
+elif [ ${#DEAD_REPO_USERS[@]} -gt 0 ]
 then
-/bin/echo -e "${SHOSTNAME}\tCondor Health check\t${exit_code}\t${TellNagios}"| /usr/sbin/send_nsca -H $NAGIOS_SERVER -c /etc/nagios/send_nsca.cfg >/dev/null
+	NAGIOS_MESG=$TEST_MESG
+	for dead in ${DEAD_REPO_USERS[@]}
+		do
+			CONDOR_MESG="$CONDOR_MESG && (regexp(\"$dead\", Owner) =?= False)"
+		done
+		EXIT_CODE=1  	                   # Nagios warn
 fi
-# echo our message to condor
-echo $mesg
-echo "NODE_STATUS = \"$TellNagios\""
-# exit
-exit ${exit_code}
+# end of cvmfs checks
+## End of non-fatal checks
 
+# Now just do an exit with correct codes..
+debug "EXIT_CODE    $EXIT_CODE"
+echo $CONDOR_MESG
+echo "NODE_STATUS = \"$NAGIOS_MESG\""
+if [ $DEBUG_VAL -gt 0 ]
+then
+	debug "Nrpe command is:"
+	echo "/bin/echo -e \"${SHOSTNAME}\tCondor Health check\t${EXIT_CODE}\t${NAGIOS_MESG}\" | /usr/sbin/send_nsca -H ${NAGIOS_SERVER} -c /etc/nagios/send_nsca.cfg >/dev/null"
+else
+	/bin/echo -e "${SHOSTNAME}\tCondor Health check\t${EXIT_CODE}\t${NAGIOS_MESG}" | /usr/sbin/send_nsca -H ${NAGIOS_SERVER} -c /etc/nagios/send_nsca.cfg >/dev/null
+fi
+# We don't bother logging non-fatal runs.
+exit ${EXIT_CODE}
 
